if: tag IS blank

language: node_js

services: docker

node_js:
  - 10

cache:
  directories:
    - node_modules

stages:
  - test
  - release

jobs:
  include:
    - stage: test
      script: true

    - stage: release
      node: 9
      script: npx semantic-release
      if: branch = master
      if: type IN (push)
