_extends: .github

repository:
  name: [name]
  description: [description]
  topics: [topics]
  homepage: [homepage]
  private: [private]
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
