language: node_js

services: docker

node_js:
  - 9
  - 8
  - 6

cache:
  directories:
    - node_modules

stages:
  - cache
  - test
  - coverage
  - release

before_install: export PATH=$PATH:$TRAVIS_BUILD_DIR/.scripts

jobs:
  include:
    - stage: cache
      node: 9
      script: true

    - stage: coverage
      node: 9
      before_script: test-reporter before-build
      after_script: test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - stage: release
      node: 9
      script: npx semantic-release
      if: branch = master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
