if: tag IS blank

language: node_js

services: docker

node_js:
  - 9
  - 8
  - 6

cache:
  directories:
    - ~/docker
    - node_modules

stages:
  - cache
  - test
  - coverage
  - release

before_install: export PATH=$PATH:$TRAVIS_BUILD_DIR/.scripts

jobs:
  include:
    - stage: cache
      node: 9
      script: codeclimate engines:install

    - stage: coverage
      node: 9
      before_script: test-reporter before-build
      script: npm run test:tap
      after_script: test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - stage: release
      node: 9
      install: npm install --production
      script: npx semantic-release
      if: branch = master
      if: type IN (push)


before_script:
  - sudo service docker stop
  - if [ "$(ls -A /home/travis/docker)" ]; then echo "/home/travis/docker already set"; else sudo mv /var/lib/docker /home/travis/docker; fi
  - sudo bash -c "echo 'DOCKER_OPTS=\"-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -g /home/travis/docker\"' > /etc/default/docker"
  - sudo service docker start

before_cache:
  - sudo service docker stop
  - sudo chown -R travis ~/docker
