if: tag IS blank

language: node_js

node_js: 10

stages:
  - test
  - release

jobs:
  include:
    - stage: test
      install: skip
      script: skip

    - stage: release
      node: 10
      install: npm install --no-save @ahmadnassri/semantic-release
      script: npx semantic-release
      if: branch = master
      if: type IN (push)
